### ISSUE TITLE
Endpoint: GET /Clients

### ISSUE THREAD

**Issue by katherinj** [Giansingh4710/cs490_exercise_app_backend#17]
**Description:**
an endpoint that lists all clients for the coach
will be used to display a summary list of clients in the application, showing basic information for each client

**Request body:** n/a
**Query Params:** n/a
**Path Params:** n/a

**JSON Response:**
a JSON array of user objects. Each object must include UserID, FirstName, and LastName.
ex: 
```
[
    {"UserID": " ", "FirstName": " ", LastName": " "}, 
    ..... , 
    {"UserID": " ", "FirstName": " ", LastName": " "} 
]
```

**Comment by Giansingh4710** [comment]
if you need clients for a specific coach, isn't the coachid needed from the frontend In the query params?

**Comment by Giansingh4710** [comment]
route will now be '/coach/:CoachID/clients’ as discussed on discord

**Comment by Giansingh4710** [comment]
![Screenshot 2023-12-02 at 1 47 27 PM](https://github.com/Giansingh4710/cs490_exercise_app_backend/assets/73843250/0ec4018e-6234-4e56-a926-2b8ddfb4ff13)
