### ISSUE TITLE
Endpoint: GET /Requests/OpenClientRequests

### ISSUE THREAD

**Issue by katherinj** [Giansingh4710/cs490_exercise_app_backend#19]
**Description:**
 an endpoint to retrieve a list of unanswered coaching requests
each entry should include the request ID, along with the coach's ID, first name, and last name
the list should be sorted alphabetically by the coach's name
will be used on the "Explore Coaches" page under the "My Requests" tab so a client can view all requests they have sent out to coaches 

**Request body:** n/a
**Query Params:** n/a
**Path Params:** n/a

**JSON Response:** a JSON array where each element is an object containing the request ID and an embedded object for the coach's details, and should be sorted alphabetically by the coach's first name
ex:

```
[
    {
    "RequestID": 123,
    "Coach": {
      "CoachID": 234,
      "FirstName": "John",
      "LastName": "Doe" 
     }
  }, 
     ...
  {
    "RequestID": 124,
    "Coach": {
      "CoachID": 235,
      "FirstName": "Jane",
      "LastName": "Smith"
    }
  }
]
```

**Comment by Giansingh4710** [comment]
If this is only open requests, then would that mean only pending requests right? or no?

**Comment by katherinj** [comment]
right
