### ISSUE TITLE
Endpoint: GET /Requests/OpenCoachRequests

### ISSUE THREAD

**Issue by katherinj** [Giansingh4710/cs490_exercise_app_backend#20]
**Description:**
 an endpoint to retrieve a list of unanswered coaching requests that a coach has not answered 
each entry should include the request ID, along with the user's ID, first name, and last name
the list should be sorted alphabetically by the clients name
will be used on the "My Clients" page under "New Requests" tab where a coach will be able to see a list of all their unanswered requests from clients 

**Request body:** n/a
**Query Params:** n/a
**Path Params:** n/a

**JSON Response:** a JSON array where each element is an object containing the request ID and an embedded object for the client's details, and should be sorted alphabetically by the clients first name
ex:

```
[
    {
    "requestID": 123,
    "user": {
      "userID": 234,
      "firstName": "John",
      "lastName": "Doe" 
     }
  }, 
     ...
  {
    "requestID": 124,
    "user": {
      "userID": 235,
      "firstName": "Jane",
      "lastName": "Smith"
    }
  }
]
```

**Comment by Giansingh4710** [comment]
'each entry should include the request ID, along with the coach's ID, first name, and last name'
here did you mean user's id. 

basically, this is for a coach and he is viewing all the requests he has gotten. is this correct?

**Comment by katherinj** [comment]
right, ill update the description

**Comment by katherinj** [comment]
updated json to use camel case as agreed on discord

**Comment by Giansingh4710** [comment]
done.
endpoints:
/request/openClientRequest
/request/openCoachRequests

![Screenshot 2023-12-05 at 7 48 34 PM](https://github.com/Giansingh4710/cs490_exercise_app_backend/assets/73843250/169d15ba-0b61-4b56-a61e-7ba7e5f15034)
