### ISSUE TITLE
Endpoint: GET '/coach/search?name={searchTerm}&specialization={selectedSpecialization}&maxPrice={selectedMaxPrice}&state={selectedState}&city={selectedCity}

### ISSUE THREAD

**Issue by katherinj** [Giansingh4710/cs490_exercise_app_backend#23]
Adding onto the already existing endpoint that returns a list of coaches based on a searchTerm

Description:
an endpoint to allow searching for coaches by:
* name
* specialization
* max price
* state
* city 

Query Params: 
name
specialization
max price
state 
city

JSON Response: 
a JSON array of coach objects sorted alphabetically by name
Each object must include CoachID, FirstName, and LastName.
ex: {"Coaches": {"CoachID": " ", "FirstName": " ", LastName": " "}, ..... , {"CoachID": " ", "FirstName": " ", LastName": " "} }

**Comment by Giansingh4710** [comment]
also can the endpoint for this be '/coach/search?name={searchTerm}&goal={selectedGoal}' ?

**Comment by Julian-Hame** [comment]
Should be accessible in dev branch.

Below are a few examples of how to access the endpoint:
[This should fetch a list of every coach](http://localhost:1313/coaches/search?name=&specialty=&maxPrice=500&state=&city=)

[This should fetch a list of every coach with the letter a in their names whose specialty involves strength, and is located in a state with "New" in its name (New York/New Jersey etc.) and is located in a city with "New" in its name (New York City/Newark etc.)](http://localhost:1313/coaches/search?name=a&specialty=strength&maxPrice=500&state=New&city=New)

[This should fetch a coach named Benoit Heggman whose specialty is weight loss, priced under $50, from Sioux Falls, South Dakota](http://localhost:1313/coaches/search?name=Benoit_Heggman&specialty=weight_loss&maxPrice=50&state=South_Dakota&city=Sioux_Falls)
