### ISSUE TITLE
ENDPOINT: GET /meals

### ISSUE THREAD

**Issue by jp0221** [Giansingh4710/cs490_exercise_app_backend#27]
I need an endpoint for retrieving meals for a user to display them in a table on the Logging Activities/User Dashboard page. The endpoint should retrieve the meal type(Breakfast/Lunch/Dinner/Snack), food name, and the number of calories from the food intake table.

**Comment by Rushp0** [comment]
The database table also columns for protein, fat and carbs is that data you need as well?
