### ISSUE TITLE
ENDPOINT: GET /exercise

### ISSUE THREAD

**Issue by jp0221** [Giansingh4710/cs490_exercise_app_backend#31]
I am working on creating the exercise bank and in order to display the exercises from the database I need an endpoint.
// Example exercise data
[
  {
    "id": 1,
    "name": "Squat",
    "description": "Compound exercise for the legs.",
    "muscleGroup": "Legs"
  },
  {
    "id": 2,
    "name": "Bench Press",
    "description": "Compound exercise for the chest.",
    "muscleGroup": "Chest"
  },
  // Add more exercises as needed
]

**Comment by Julian-Hame** [comment]
This should be accessible via:
http://localhost:1313/exercises/allExercises

As of writing this, it's on dev branch. 
Also, since the exercise table lacks a description column, I replaced that with the type and difficulty columns.
