### ISSUE TITLE
Endpoint: getting all states that coaches are available in

### ISSUE THREAD

**Issue by katherinj** [Giansingh4710/cs490_exercise_app_backend#34]
** not sure on backend where this route would be best placed, please add the route where you see fit and update this issue, or add as a comment ** 

background: on front end, a user will be able to filter by location, meaning state and cities
They will be able to choose "Any State" or a specific state
If they choose a specific state, they will have the option to keep the city filter as "Any City" or choose a specific city from that state

Description: an endpoint that returns all states and cities within those states that coaches are available in, in order to display these states and cities as part of the location filter feature 

Response should be an array in the following format, in alphabetical order for the states, and the cities for each state
``
[
     {
        "State": "Arizona",
        "Cities": ["Chandler", "Mesa", "Phoenix", "Tucson"]
    },
    {
        "State": "California",
        "Cities": ["Los Angeles", "San Diego", "San Francisco", "San Jose"]
    },
    {
        "State": "New Jersey",
        "Cities": ["Elizabeth", "Jersey City", "Newark", "Paterson"]
    },
]
``

**Comment by Julian-Hame** [comment]
Should be accessible via 
[http://localhost:1313/coaches/cities](http://localhost:1313/coaches/cities)

**Comment by katherinj** [comment]
is there a way that the cities can be returned in an array format? right now it is just a string 
if not, I will find a way to do it on the front end

**Comment by Julian-Hame** [comment]
> is there a way that the cities can be returned in an array format? right now it is just a string if not, I will find a way to do it on the front end

I changed the query to use JSON_ARRAYAGG so it should return cities in the proper format now
