### ISSUE TITLE
Endpoint: getting all specializations for available coaches

### ISSUE THREAD

**Issue by katherinj** [Giansingh4710/cs490_exercise_app_backend#36]
Description: an endpoint that returns all specializations that a coach can pick for themselves

will be used to populate the specialization drop down filter on front end explore coaches page 

response example: 
{"Specialization 1", "Specialization2" ,..."Specialization"}

**Comment by Julian-Hame** [comment]
Should be accessible via: [http://localhost:1313/coaches/specializations](url)
