### ISSUE TITLE
Endpoint: getting the status of a request between a client and a coach

### ISSUE THREAD

**Issue by katherinj** [Giansingh4710/cs490_exercise_app_backend#37]
On front end, when a user is browsing for coaches, and selects a coach to view their details, the user will see a "Request" button if there is no request yet, or "Cancel request" button if there is a request sent out already 

Possible endpoint structure: GET /Requests/Status?userID=123&coachID=456

front end is able to provide coachID and userID 

Description: an endpoint that returns the status of a request
example json: 
if a request exists for that specific coach from that client,
{
  "exists": true,
  "status": "Pending",
  "requestId": 789
}

if a request does not exist: 
{
  "exists": false
}

** Note: this endpoint may be combined with the /Coaches/:coachID endpoint, and the request status may be sent back when getting the details of that specific coach
I am not sure which approach would better/easier on backend, please let me know which format you end up using and I will update front end accordingly ****

**Comment by Julian-Hame** [comment]
Pushed to dev branch, should be accessible via _http://localhost:1313/request/status?userid=123&coachID=456_

With the database populated by the large mock data script:
[This should return info for an existing request](http://localhost:1313/request/status?userid=2&coachID=10)
[This should return false for no existing request](http://localhost:1313/request/status?userid=2&coachID=2)
