### ISSUE TITLE
POST ./recordActivity

### ISSUE THREAD

**Issue by jp0221** [Giansingh4710/cs490_exercise_app_backend#46]
Create an endpoint for the daily survey on the client side. Client fills out the weight, water input, mood and clicks submit.
{
  "waterData": { /* 12 floz */ },
  "weightData": { /* 128 */ },
  "moodData": { /* Unhappy */ }
}
These are examples of the data being inputted. The water modal will input a numeric value and a unit value from a dropdown.

**Comment by Rushp0** [comment]
moved endpoint to POST /logActivity/recordActivity

**Comment by Rushp0** [comment]
moved endpoint to POST logActivity/recordDailySurvey. Request format changed to:
{
   waterData: {
      amount: 12,
      unit: "fl oz"
   },
   weightData: 165,
   moodData: "Unhappy"
}
