### ISSUE TITLE
Endpoint: GET /Coaches

### ISSUE THREAD

**Issue by katherinj** [Giansingh4710/cs490_exercise_app_backend#7]
**Description:**
an endpoint that lists all coaches
will be used to display a summary list of coaches in the application, showing basic information for each coach

**Request body:** n/a
**Query Params:** n/a
**Path Params:** n/a

**JSON Response:**  a JSON array of coach objects. Each object must include CoachID, FirstName, and LastName.
ex: {"Coaches": {"CoachID": " ", "FirstName": " ", LastName": " "}, ..... , {"CoachID": " ", "FirstName": " ", LastName": " "} }

**Comment by Julian-Hame** [comment]
You should be able to visit this endpoint at:
[http://localhost:1313/api/coaches](url)
