### ISSUE TITLE
GET '/dailyweight' Endpoint

### ISSUE THREAD

**Issue by jp0221** [Giansingh4710/cs490_exercise_app_backend#70]
I need a daily weight endpoint to use to record for the weight progress graph.
{
  "data": [
    {
      "date": "2023-01-01",
      "weight": 150
    },
    {
      "date": "2023-01-02",
      "weight": 149
    },
    // ... more entries
  ]
}

**Comment by Julian-Hame** [comment]
Pushed to dev branch, should be accessible via _http://localhost:1313/logActivity/dailyWeight?userID=userID_.

So if you want to get the weight progress of user 11, you would use:
[http://localhost:1313/logActivity/dailyWeight?userID=11](http://localhost:1313/logActivity/dailyWeight?userID=11)
