### ISSUE TITLE
Endpoint: UPDATE /request

### ISSUE THREAD

**Issue by katherinj** [Giansingh4710/cs490_exercise_app_backend#74]
an endpoint to update a request status as a coach or client: 
given a requestID:
ex: {requestID: 123, status: "Decline"}

or we can do UPDATE /request/{requestID}
and json can be: {status: "Decline"} 

a coach can update status to: decline or accept
a client can cancel their request (I'm not sure on backend how we would handle this? deleting the request as a whole?) 

please let me know if front end needs to send the userID or if you are able to extract from token

**Comment by Julian-Hame** [comment]
Added three endpoints, /request/accept, /request/decline and /request/cancel.

[http://localhost:1313/request/accept?requestID=8](http://localhost:1313/request/accept?requestID=8) should change request with ID 8's status to "Accepted"
[http://localhost:1313/request/decline?requestID=8](http://localhost:1313/request/decline?requestID=8) should change request with ID 8's status to "Declined"
[http://localhost:1313/request/cancel?requestID=8](http://localhost:1313/request/cancel?requestID=8) should delete request with ID 8 from the database

**Comment by Julian-Hame** [comment]
Update: For the cancellation endpoint, I've changed the route method from _router.get_ to _router.delete_ for the sake of good practice. This won't affect the URI used to access it, but make sure to treat it with a DELETE request rather than a GET.
