### ISSUE TITLE
ENDPOINT: GET /client/{userID}

### ISSUE THREAD

**Issue by katherinj** [Giansingh4710/cs490_exercise_app_backend#75]
get a specific clients info:
* ensure that only a clients coach can view their info 

expeted response: 
{
userID: 123, 
firstName: tom, 
lastName: doe,  
goal: "their goal", 
dailySurvey: {mentalState: "", foodIntake: "", waterIntake:"", weightProgress: "", workoutPlan: ""}
}

should dailySurvey return their most recent dailysurvey they have completed?

**Comment by Julian-Hame** [comment]
Should be accessible via _http://localhost:1313/coaches/clientInfo?userID=userID_

So to get information on user 2, you would use:
[http://localhost:1313/coaches/clientInfo?userID=2](http://localhost:1313/coaches/clientInfo?userID=2)
