### ISSUE TITLE
Delete workout

### ISSUE THREAD

**Issue by demetrisperdikos** [Giansingh4710/cs490_exercise_app_backend#80]
for the manage workouts from the workout bank we should just delete a workout when you click the delete button

**Comment by Julian-Hame** [comment]
Endpoint can be found at _http://localhost:1313/exercises/deleteExercise?exerciseID=exerciseID_

So for example, to delete exercise with ID 18 from the exercise bank you would use:
[http://localhost:1313/exercises/deleteExercise?exerciseID=18](http://localhost:1313/exercises/deleteExercise?exerciseID=18)
