### ISSUE TITLE
accept and decline incoming coach requests

### ISSUE THREAD

**Issue by demetrisperdikos** [Giansingh4710/cs490_exercise_app_backend#83]

**Comment by Julian-Hame** [comment]
I split this into two separate endpoints, accessible via /coachApply/accept and /coachApply/deny.

So to accept a request with ID 11, you would use:
[http://localhost:1313/coachApply/accept?coachRequestID=11](http://localhost:1313/coachApply/accept?coachRequestID=11)

And to deny a deny a request with ID 14, you would use:
[http://localhost:1313/coachApply/deny?coachRequestID=14](http://localhost:1313/coachApply/deny?coachRequestID=14)
