### ISSUE TITLE
Endpoint: GET /Coaches?name={SearchTerm}

### ISSUE THREAD

**Issue by katherinj** [Giansingh4710/cs490_exercise_app_backend#9]
**Description:**
an endpoint to allow searching for coaches by name
will enable users to find coaches using a search term

**Request body:** n/a
**Query Params:** name
**Path Params:** n/a

**JSON Response:**  a JSON array of coach objects. Each object must include CoachID, FirstName, and LastName.
ex: {"Coaches": {"CoachID": " ", "FirstName": " ", LastName": " "}, ..... , {"CoachID": " ", "FirstName": " ", LastName": " "} }

notes: 
filters coaches based on the provided name, considering partial matches and case sensitivity

**Comment by Julian-Hame** [comment]
You should be able to access this endpoint with:
http://localhost:1313/api/coaches-search-name?name=searchTerm

So for example if you wanted to search for a user named Elliot you would go to:
[http://localhost:1313/api/coaches-search-name?name=elliot](url)
