### ISSUE TITLE
Endpoint: coach terminates a client

### ISSUE THREAD

**Issue by katherinj** [Giansingh4710/cs490_exercise_app_backend#90]
given a userID for a coaches's client, the coach can terminate a client (will not show up in their client list, and that client will not have a coach assigned anymore)

**Comment by Julian-Hame** [comment]
Should be accessible via: /coaches/terminate

So to terminate user with ID 2 from their coach, you would use:
[http://localhost:1313/coaches/terminate?userID=2](http://localhost:1313/coaches/terminate?userID=2)
This will set the CoachID of that user to NULL
